[routers]
R1 ansible_host=192.168.70.10
R2 ansible_host=192.168.70.20
R3 ansible_host=192.168.70.30

[routers:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_user=admin
ansible_network_os=cisco.ios.ios
ansible_ssh_common_args='-o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa'
